### ISSUE TITLE
Filtrado de nombre insuficiente

### ISSUE THREAD

**Issue by ulvida** [UdelaRInterior/ansible-role-proxmox-create-lxc#1]
En [la línea 127 de tasks/main.yml](https://github.com/UdelaRInterior/ansible-role-proxmox-create-lxc/blob/ec7ea1e27ded7a5e5822d5a731df4c446b04b82a/tasks/main.yml#L127) hay que filtar mejor el nombre de _guest_proxmox, porque si no da "falsos positivos" con los otros que lo contengan:   

```shell
< TASK [crear_lxc : Extraer el número de VM] >
 --------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [ta.interior.edu.uy -> guri.interior.edu.uy]
 __________________________
< TASK [crear_lxc : debug] >
 --------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [ta.interior.edu.uy] => {
    "VMID": {
        "changed": true, 
        "cmd": "pct list | grep \"ta\" | cut -f 1 -d ' '", 
        "delta": "0:00:00.768197", 
        "end": "2019-01-17 17:56:28.451441", 
        "failed": false, 
        "rc": 0, 
        "start": "2019-01-17 17:56:27.683244", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "VMID\n103\n106", 
        "stdout_lines": [
            "VMID", 
            "103", 
            "106"
        ]
    }
}
```

**Comment by santiagomr** [comment]
Agregando el parámetro '-w' a grep (Ya corregido en [este commit](https://github.com/UdelaRInterior/ansible-role-proxmox-create-lxc/commit/60abbfd23231f951592d554515d11fbaa68a1b10) ) se solucionan los falsos positivos al filtrar solo el guest con el nombre exacto y no los guests cuyo nombre pudiera contener el buscado.

**Comment by ulvida** [comment]
Era tarde e hice otras modificaciones, pero no pateó. Así que considerado cerrado!
