### ISSUE TITLE
[FEATURE] Container description parameter

### ISSUE THREAD

**Issue by ulvida** [UdelaRInterior/ansible-role-proxmox-create-lxc#11]
I would like to set with ansible the description of the container in Proxmox VE. 

I think we should handle in the role the [parameter description](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html#parameter-description) of the proxmox module (or now: collection?)

(Moreover, there is now a concept of [proxmox dynamic inventory](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_inventory.html) with this module. Maybe it's useful for us)

**Comment by ulvida** [comment]
I create the branche [namespace](https://github.com/UdelaRInterior/ansible-role-proxmox-create-lxc/tree/namespace) to work out this feature, and I will address simultaneously Role's variables namespace, #9.

**Comment by ulvida** [comment]
`description` parameter is only available in the [community collection module, for ansible 2.10](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html).

**Comment by santiagomr** [comment]
Use of collections in the role has already been implemented and [proposed here](https://github.com/UdelaRInterior/ansible-role-proxmox-create-lxc/pull/14). Handling, among others, the `description` parameter.
