### ISSUE TITLE
[BUG] v5.0.0 review

### ISSUE THREAD

**Issue by ulvida** [UdelaRInterior/ansible-role-proxmox-create-lxc#16]
I'm trying to upgrade my playbooks and variables to v.5.0.0 of th role, and I'm coming into errors, with quite cryptic output messages, hard to analyse: 
 ```
TASK [udelarinterior.proxmox_create_lxc : Create the container] *****************************************************************************************************************************
task path: /home/ulvida/tech/interior/roles/ansible-role-proxmox-create-lxc/tasks/main.yml:56
fatal: [<myhost> -> <mynode>]: FAILED! => {"changed": false, "msg": "creation of lxc VM 194 failed with exception: 403 Forbidden: {\"data\":null}"}

PLAY RECAP **********************************************************************************************************************************************************************************
 ```
So I'm starting here a kind of "review post merge".

**Comment by santiagomr** [comment]
What values do you have defined for the host vars?

**Comment by ulvida** [comment]
After our conversation yesterday, I confirm that it was because of the use of the variable:
```
pve_lxc_features:
  - nesting=1
 ```
 with an API non root user that, though it has PVE Administrator rights,you told me that this is not "full superuser", so the error.

The module's message is really cryptic,maybe we should report it and document it in the role's doc. Under the example: "requires root as API pve node user".
