### ISSUE TITLE
[BUG] Unable to create mount point to existing folder on host file system

### ISSUE THREAD

**Issue by sumnerboy12** [UdelaRInterior/ansible-role-proxmox-create-lxc#21]
**Describe the bug**
Using `pve_lxc_mounts` to create a  mount to an existing folder (`/nas/media/music`) on the host file system fails with;

`unable to create CT 112 - directory '/nas/media/music:32' does not exist`

If no size is included in the mount config, it defaults to 32 and appends this to the config option. But when mounting a path on the host file system we don't want to specify a size.

**Expected behavior**
If no size is specified then omit the `:<size>` from the mount point config and simply mount the path on the host file system.

**Characteristics of the execution environment (please complete the following information):**
 - OS (local and remote if applicable): [e.g. Debian 9.5]
 - Tools used [e.g. Ansible 2.7, Python 3.5]

**Comment by ulvida** [comment]
Hi @sumnerboy12 . Thanks for your contribution. 

First: we have migrated this role to [cielito.proxmox collection](https://galaxy.ansible.com/cielito/proxmox), we wsill maintain this code and deprecate present github repo. 

Second: I'm afraid what you consider a role's bug is a limitation behaviour of the [mounts parameter of the community.general.proxmox module](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html#parameter-mounts), which morover is very  poorly documented. 

If you have a solution welcome [to propose it here](https://git.interior.edu.uy/cielito/proxmox/-/issues), but sorry, I don't see how to easily solve your requirement.

**Comment by sumnerboy12** [comment]
Understood, and thanks for the pointers. Here is my work-around in case someone else comes across this;

```
pve_lxc_additional_configurations:
- regexp: '^mp0:'
  line: 'mp0:/nas/media/music,mp=/mnt/music,ro=1'
  state: present
```
